global:
    ros__parameters:
        deadman: false

path_server:
    ros__parameters:
        name: "path_server"
        autostart: true
        max_linear_speed: 1.14
        max_angular_speed: 1.14
        odom_topic: "odom"
        fix_topic: "gps"

deadman:
    ros__parameters:
        name: "deadman"
        joystick_topic: "joy"
        deadman_button: 4
        start_topic: "nav/start"
        stop_topic: "nav/stop"
        pause_topic: "nav/pause"
